trajectory_evaluator:
  type: "RRTStarEvaluatorAdapter"

  following_evaluator:
    type: "ContinuousYawPlanningEvaluator"
    n_directions: 12
    n_sections_fov: 3
    update_range: 3.0
    update_gain: 0.0
    update_sections_separate: false

    following_evaluator:
      type: "ClassConfidenceEvaluator"
      visualize_sensor_view: true
      accurate_frontiers: true
      checking_distance: 2.0
      bounding_volume_args: "/target_bounding_volume"

      frontier_voxel_weight: 1.0
      new_voxel_weight: 0.0
      min_impact_factor: 0.01
      ray_angle_x: 0.002454
      ray_angle_y: 0.002681

      sensor_model:
        type: "IterativeRayCaster"
        sampling_time: 0.0
        ray_length: 5.0
        focal_length: 320.0
        resolution_x: 172 # 640-90/172-30/127-22.5 deg fov
        resolution_y: 480
        downsampling_factor: 5.0

      cost_computer:
        type: "SegmentTime"

      value_computer:
        type: "GlobalNormalizedGain"

      next_selector:
        type: "SubsequentBest"