scene_file: /media/giuliano/wd_ssd/datasets/replica/room_2/habitat/mesh_semantic.ply

initial_position:
  x: 0.0
  y: 0.0
  z: 0.0

map_bounding_volume:
  x_min: -4
  x_max: 4
  y_min: -4
  y_max: 4
  z_min: -2
  z_max: 2

target_bounding_volume:
  x_min: -5
  x_max: 5 
  y_min: -5
  y_max: 5
  z_min: -3
  z_max: 3
