single_tsdf_tracked_instance_type: 0

id_tracker:
  type: single_tsdf
  verbosity: 1

  # Single TSDF tracker params
  voxel_size: 0.05
  truncation_distance: -2
  voxels_per_side: 16
  use_class_layer: true
  use_detectron: true
  use_detectron_panoptic: true
  use_class_for_instance_tracking: false
  min_new_instance_size: 500
  tracking_metric: IoU # IoU, overlap
  match_acceptance_threshold: 0.6
  classification:
    type: panoptic_weight