# General Params
verbosity: 3
is_single_tsdf: true
use_threadsafe_submap_collection: true
use_transform_caching: true
transform_lookup_time: 0.1
global_frame_name: world
visualization_interval: -1.0
data_logging_interval: -1.0
print_timing_interval: 0.0
max_input_queue_length: 1000
ros_spinning_threads: 8

labels:
  type: csv
  file_name: /home/albanesg/robostack_catkin_ws/src/active_panoptic_mapping/panoptic_mapping_evaluation/config/mapper/nyu40_detectron_labels.csv

camera:
  verbosity: 1
  width: 320 # Px
  height: 240
  vx: 159.579023
  vy: 121.469512
  fx: 288.795332
  fy: 289.364901
  max_range: 5 # m
  min_range: 0.1

id_tracker:
  type: single_tsdf # ground_truth, projective, detectron, single_tsdf
  verbosity: 4

  # Single TSDF tracker params
  voxel_size: 0.05
  truncation_distance: -2
  voxels_per_side: 16
  use_class_layer: true
  use_detectron: true
  use_detectron_panoptic: true
  min_new_instance_size: 500
  use_class_for_instance_tracking: false
  use_one_to_one_matching: false
  use_uncertainty: false
  tracking_metric: IoU # IoU, overlap
  match_acceptance_threshold: 0.6
  classification:
    type: variable_count

tsdf_integrator:
  type: single_tsdf
  verbosity: 1

  # Projective
  use_weight_dropoff: true
  use_uncertainty: false
  max_weight: 10000
  interpolation_method: adaptive # nearest, bilinear, adaptive
  integration_threads: 8

submap_allocator:
  type: semantic # semantic
  verbosity: 1

  # submaps
  voxels_per_side: &voxels_per_side 16
  truncation_distance: -2 # negative = #vs
  use_class_layer: true

  # Meshing
  clear_foreign_voxels: false
  required_belonging_corners: 1

  # Semantic
  small_instance_voxel_size: 0.05
  medium_instance_voxel_size: 0.05
  large_instance_voxel_size: 0.05
  background_voxel_size: 0.05
  unknown_voxel_size: 0.05

freespace_allocator:
  type: monolithic # monolithic
  verbosity: 1
  voxels_per_side: *voxels_per_side
  truncation_distance: -2
  voxel_size: 0.3

visualization:
  submaps:
    type: single_tsdf
    verbosity: 1
    color_mode: classes # color, normals, classes, instances, classification
    visualization_mode: all # all
    submap_color_discretization: 20
    visualize_mesh: true
    visualize_tsdf_blocks: true
    visualize_free_space: true
    visualize_bounding_volumes: true
    include_free_space: true
    mesh_min_weight: 0.000001

  planning:
    verbosity: 1
    visualize_slice: true
    slice_resolution: 0.1
    slice_height: -0.5

  tracking:
    verbosity: 1
    visualize_tracking: true

data_writer:
  type: log
  verbosity: 1
  output_directory: /tmp
    
