initial_position:
  x: 0.0
  y: 0.0
  z: 0.0
map_bounding_volume:
  x_max: -4
  x_min: 1
  y_max: -6
  y_min: 3
  z_max: 5
  z_min: -10
target_bounding_volume:
  x_max: -4
  x_min: 1
  y_max: -6
  y_min: 3
  z_max: 5
  z_min: -10
