initial_position:
  x: 0.0
  y: 0.0
  z: 0.0
map_bounding_volume:
  x_max: 4
  x_min: -2
  y_max: 1
  y_min: -5
  z_max: 1.5
  z_min: -1.0
target_bounding_volume:
  x_max: 4
  x_min: -2
  y_max: 1
  y_min: -5
  z_max: 1.5
  z_min: -1.0
