initial_position:
  x: 0.0
  y: 0.0
  z: 0.0
map_bounding_volume:
  x_max: 6
  x_min: -3
  y_max: 5
  y_min: -10
  z_max: 4
  z_min: -2
target_bounding_volume:
  x_max: 6
  x_min: -3
  y_max: 5
  y_min: -10
  z_max: 4
  z_min: -2
