initial_position:
  x: 0.0
  y: 0.0
  z: 0.0
map_bounding_volume:
  x_max: -1
  x_min: 3
  y_max: -6
  y_min: 1
  z_max: 2
  z_min: -3
target_bounding_volume:
  x_max: -1
  x_min: 3
  y_max: -6
  y_min: 1
  z_max: 2
  z_min: -3
