agent:
  embodied: true
  sensor_height: 0
  image_width: 640
  image_height: 480

simulator:
  enable_physics: false
  sim_rate: 60
  sensor_rate: 3
  control_rate: 30
  odom_pub_rate: 15

position_controller:
  kp_x: 0.6
  kp_y: 0.6
  kp_z: 0.6
  kp_yaw: 1.0
  kd_x: 0.3
  kd_y: 0.3
  kd_z: 0.3
  kd_yaw: 0.6
  max_horz_speed: 1.0
  max_vert_speed: 1.0
  max_yaw_rate_degrees: 15.0
  reached_thresh_xyz: 0.05
  reached_thresh_yaw_degrees: 0.05
